#!/usr/bin/env node
/**
 * Fetch the portable Node.js distribution for each Tauri target and lay out
 * the two artifacts the bundle needs:
 *
 *   src-tauri/binaries/node-<targetTriple>[.exe]   — externalBin sidecar
 *   node-dist/<distTag>/bin/{npm,npx,corepack}     — scripts on PATH
 *   node-dist/<distTag>/lib/node_modules/{npm,corepack}
 *
 * Only `node` itself is a real executable; npm/npx/corepack are small scripts
 * from the official dist that run under `node`. The Rust shell writes a `node`
 * shim into the app-data bin dir at first launch so `env node` (used by those
 * scripts and by the harness's shells) resolves to the renamed sidecar.
 *
 * Usage: node scripts/fetch-node.mjs [target ...]
 *   targets default to the host; pass e.g. aarch64-apple-darwin
 *   x86_64-apple-darwin x86_64-pc-windows-msvc to prepare a cross bundle.
 * Env: DSH_NODE_VERSION  node version to bundle (default 24.15.0)
 *      DSH_NODE_MIRROR   dist base URL (default https://nodejs.org/dist;
 *                        use https://npmmirror.com/mirrors/node in CN)
 */

import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, rmSync, copyFileSync, chmodSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const DESKTOP_DIR = dirname(dirname(fileURLToPath(import.meta.url)))
const VERSION = process.env.DSH_NODE_VERSION || '24.15.0'
const MIRROR = (process.env.DSH_NODE_MIRROR || 'https://nodejs.org/dist').replace(/\/+$/, '')

/** distTag -> { triple, os, arch, ext } */
const TARGETS = {
  'darwin-arm64': { triple: 'aarch64-apple-darwin', os: 'darwin', arch: 'arm64', ext: 'tar.gz' },
  'darwin-x64': { triple: 'x86_64-apple-darwin', os: 'darwin', arch: 'x64', ext: 'tar.gz' },
  'win32-x64': { triple: 'x86_64-pc-windows-msvc', os: 'win', arch: 'x64', ext: 'zip' },
}

/**
 * Write an executable shim that runs a bundled package entry under the
 * bundled Node sidecar (DSH_DESKTOP_NODE, set by the Rust shell) or `node`.
 * `entry` is relative to the shim's directory.
 */
function writeToolShim(binDir, name, entry, windows) {
  const sh = join(binDir, name)
  writeFileSync(sh, [
    '#!/bin/sh',
    `# Generated by DSH Desktop: bundled ${name}, running the package entry.`,
    'NODE="${DSH_DESKTOP_NODE:-node}"',
    `exec "$NODE" "$(dirname "$0")/${entry}" "$@"`,
    '',
  ].join('\n'))
  chmodSync(sh, 0o755)
  if (windows) {
    const cmd = join(binDir, name + '.cmd')
    const winEntry = entry.replaceAll('/', '\\')
    writeFileSync(cmd, [
      '@echo off',
      'if defined DSH_DESKTOP_NODE (',
      `  "%DSH_DESKTOP_NODE%" "%~dp0\\..\\${winEntry}" %*`,
      ') else (',
      `  node "%~dp0\\..\\${winEntry}" %*`,
      ')',
      'exit /b %ERRORLEVEL%',
      '',
    ].join('\r\n'))
  }
}

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { stdio: 'inherit', ...opts })
  if (r.status !== 0) {
    console.error(`[fetch-node] ${cmd} ${args.join(' ')} failed (${r.status})`)
    process.exit(r.status ?? 1)
  }
}

function hostTag() {
  const os = process.platform === 'darwin' ? 'darwin' : process.platform === 'win32' ? 'win32' : process.platform
  const arch = process.arch === 'arm64' ? 'arm64' : process.arch === 'x64' ? 'x64' : process.arch
  return `${os}-${arch}`
}

const requested = process.argv.slice(2)
const tags = requested.length ? requested : [hostTag()]
const cacheDir = join(DESKTOP_DIR, '.node-cache')

for (const tag of tags) {
  const t = TARGETS[tag]
  if (!t) {
    console.error(`[fetch-node] unknown target ${tag}; expected ${Object.keys(TARGETS).join(', ')}`)
    process.exit(1)
  }
  const archive = `node-v${VERSION}-${t.os}-${t.arch}.${t.ext}`
  const url = `${MIRROR}/v${VERSION}/${archive}`
  const cacheFile = join(cacheDir, archive)
  const extractDir = join(cacheDir, `node-v${VERSION}-${t.os}-${t.arch}`)
  const outBin = join(DESKTOP_DIR, 'src-tauri', 'node-dist', tag, 'bin')
  const outLib = join(DESKTOP_DIR, 'src-tauri', 'node-dist', tag, 'lib')
  const sidecarName = t.triple === 'x86_64-pc-windows-msvc' ? `node-${t.triple}.exe` : `node-${t.triple}`

  console.log(`[fetch-node] ${tag}: ${url}`)
  if (!existsSync(cacheFile)) {
    mkdirSync(cacheDir, { recursive: true })
    run('curl', ['-#', '-L', '-o', cacheFile, url])
  } else {
    console.log(`[fetch-node] cached ${archive}`)
  }

  rmSync(extractDir, { recursive: true, force: true })
  mkdirSync(extractDir, { recursive: true })
  // bsdtar (macOS + Windows 10+) handles both .tar.gz and .zip.
  run('tar', ['-xf', cacheFile, '-C', extractDir])
  const root = join(extractDir, `node-v${VERSION}-${t.os}-${t.arch}`)

  // Only the runtime scripts + their support tree are shipped: node itself
  // becomes the externalBin sidecar, npm/npx/corepack stay as resources.
  rmSync(outBin, { recursive: true, force: true })
  rmSync(outLib, { recursive: true, force: true })
  mkdirSync(outBin, { recursive: true })
  // The dist's bin/npm, bin/npx, bin/corepack are symlinks into the npm /
  // corepack packages; copyFileSync follows them and flattens the script,
  // which breaks the relative requires (`../lib/cli.js`, `./lib/corepack.cjs`).
  // Ship shims that exec the real package entry instead — same pattern as the
  // pnpm shim in prepare-runtime.mjs. DSH_DESKTOP_NODE is set by the Rust shell.
  const TOOL_ENTRIES = {
    npm: '../lib/node_modules/npm/bin/npm-cli.js',
    npx: '../lib/node_modules/npm/bin/npx-cli.js',
    corepack: '../lib/node_modules/corepack/dist/corepack.js',
  }
  for (const [name, entry] of Object.entries(TOOL_ENTRIES)) {
    writeToolShim(outBin, name, entry, t.os === 'win')
  }
  for (const name of ['npm', 'corepack']) {
    const src = join(root, 'lib', 'node_modules', name)
    if (existsSync(src)) run('rsync', ['-a', src + '/', join(outLib, 'node_modules', name) + '/'])
  }

  // The sidecar binary itself (renamed by Tauri to `node`/`node.exe`).
  const nodeBin = join(root, 'bin', 'node' + (t.os === 'win' ? '.exe' : ''))
  const sidecar = join(DESKTOP_DIR, 'src-tauri', 'binaries', sidecarName)
  mkdirSync(dirname(sidecar), { recursive: true })
  copyFileSync(nodeBin, sidecar)
  if (t.os !== 'win') {
    chmodSync(sidecar, 0o755)
    for (const name of ['npm', 'npx', 'corepack']) chmodSync(join(outBin, name), 0o755)
  }

  const size = (statSync(sidecar).size / 1e6).toFixed(1)
  console.log(`[fetch-node] ${tag}: sidecar ${sidecar} (${size} MB), node-dist ready`)
}
